import {editItem,CONTENT_FIELDS,CONTENT_LIMITS} from './model.mjs?v=20260909-transit3';
export function makeRequest(item,instruction){
  if(!instruction.trim())throw new Error('Beskriv endringen du ønsker først.');
  const content={...item.content};delete content.image;
  return `You are editing a Startuplab screen draft. This is DEMO content, not a live publication.\nUse English by default. Keep factual details unchanged unless explicitly requested. Do not invent names, dates, prices, links or claims.\nThe user's requested change:\n${instruction}\n\nCurrent item ID: ${item.id}\nCurrent revision: ${item.revision}\nCurrent content:\n${JSON.stringify(content,null,2)}\n\nReturn only a JSON object (no Markdown fences):\n${JSON.stringify({itemId:item.id,baseRevision:item.revision,patch:{title:item.content.title}},null,2)}\n\nPut only changed content fields in patch. Allowed fields: ${CONTENT_FIELDS.filter(f=>f!=='image').join(', ')}. Do not return image data or approval state. Character limits: ${JSON.stringify(CONTENT_LIMITS)}. Preserve the supplied itemId and baseRevision exactly. Text can contain newlines. Schedule instants must include a timezone. Types: event, welcome, benefit, request, notice, external, event-deck, eir, external-bleed, eir-network, alumni, timeline, event-speaker, event-spotlight, event-artwork, benefit-roundup, member-news, transit. For benefit-roundup: exactly three cards with heading, detail and note (max 36,135,90 characters); provider terms must remain unchanged unless supplied. For event-spotlight: optional cards use the same shape for three topic points. For transit: only title, eyebrow, cta and url are editable display copy; departures come from Entur and cannot be invented. For timeline: milestones is exactly six {year,title,detail} objects (max 8,48,150 characters respectively); original three photos stay fixed. For alumni only eyebrow and title appear; the supplied 14-logo grid is fixed. For eir-network: profiles is an array of exactly eight {name,bio,image} objects. Preserve supplied portrait paths; name max 48 characters, bio max 140. expertise is up to six newline-separated areas. For eir: title=name, body=competence (one area per line), detail=roles/experience, location=one factual result, cta=introduction action. External layouts render the image; hidden text fields do not appear. Screens: home, oslo, bergen. Layout is selected by type; it is not editable HTML.\n`;
}
export function applyResponse(item,raw,now){
  let data;try{data=JSON.parse(raw);}catch{throw new Error('Svaret må være ren JSON, uten kodegjerder eller forklaring.');}
  if(!data || typeof data!=='object' || Array.isArray(data) || Object.keys(data).some(k=>!['itemId','baseRevision','patch'].includes(k)))throw new Error('Svaret må inneholde itemId, baseRevision og patch.');
  if(data.itemId!==item.id)throw new Error('Svaret gjelder et annet innlegg.');
  if(data.baseRevision!==item.revision)throw new Error('Svaret gjelder en eldre versjon. Lag en ny forespørsel fra dette utkastet.');
  if(!data.patch || typeof data.patch!=='object' || Array.isArray(data.patch) || 'image' in data.patch)throw new Error('Svaret må ha en patch med tekstfelter. Bilder lastes opp i editoren.');
  return editItem(item,data.patch,now);
}
