// Editorial drafts sourced 9 September 2026. Evidence belongs in review metadata.
export function memberSamples(now=new Date()){
  const base={eyebrow:'',title:'',body:'',detail:'',location:'',cta:'',url:'',image:'',screen:'home',startsAt:new Date(+now-60000).toISOString(),endsAt:new Date(+now+86400000).toISOString()};
  return [
    ['pradeep-team-os',{type:'event-spotlight',eyebrow:'AI X',title:'From AI tools\nto team workflows.',body:'Give AI shared context. Turn recurring work into reusable skills. Decide what runs automatically and where people check the result.',expertise:'Pradeep Sankaran\nFormer SVP Product, Gelato',detail:'Date and time to be announced',location:'Proposed session · programme to be confirmed',cards:[{heading:'Shared context',detail:'Company. Product. Customers.',note:'Based on the public Team OS example.'},{heading:'Reusable skills',detail:'A repeatable way to do recurring work.',note:'Proposed session theme.'},{heading:'Human review',detail:'Clear checkpoints before action.',note:'Based on Pradeep’s Team OS presentation.'}],cta:'Watch Slack for the confirmed event',image:'assets/photos/pradeep-sankaran-linkedin.png'}],
    ['pradeep-ai-product',{type:'event-spotlight',eyebrow:'AI X',title:'From AI prototype\nto real revenue.',body:'Lessons from taking an AI product from zero to millions in revenue. What changes when the prototype has to become a business?',expertise:'Pradeep Sankaran\nFormer SVP Product, Gelato',detail:'Date and time to be announced',location:'',cards:[{heading:'A useful problem',detail:'What is worth solving?',note:'Editorial question, not a confirmed agenda.'},{heading:'A product people value',detail:'What makes them come back?',note:'Editorial question, not a confirmed agenda.'},{heading:'A business that works',detail:'What turns value into revenue?',note:'Editorial question, not a confirmed agenda.'}],cta:'Watch Slack for the confirmed event',image:'assets/photos/pradeep-sankaran-linkedin.png'}],
    ['operators-bergen',{type:'event-spotlight',eyebrow:'OPERATORS’ SESSIONS · BERGEN',title:'Building global\nfrom day one.',body:'Global ambition. Changing roles. The reality of scaling. Lessons from Dirtybit and Megacool to Medal and Tana.',expertise:'Aurora Klæboe Berg\nVP Operations, Tana',detail:'Fri 11 Sep · 13:30–15:00',location:'Startuplab Bergen\nSolheimsgaten 7C',cta:'Save your spot',url:'https://luma.com/4y68z2ei',image:'assets/photos/aurora-klaeboe-berg.png',screen:'bergen',startsAt:'2026-09-09T00:00:00+02:00',endsAt:'2026-09-11T15:00:00+02:00'}],
    ['mad-hack-agentic-loops',{type:'event-artwork',eyebrow:'AI MAD LAB · MAD HACK #4',title:'Agentic Loops.\nBuild. Break. Repeat.',body:'Team up. Build something people want. Demo it in two minutes. A full day of building with AI Mad Lab, in teams of up to three.',expertise:'Doors 09:30 · Coding 11:00 · Demos 19:00\nHost approval required',detail:'Sat 12 Sep · 10:00–20:00',location:'Startuplab Oslo\nGaustadalléen 21',cta:'Apply to join',url:'https://luma.com/5yosbokm',image:'assets/photos/ai-mad-lab-agentic-loops-cover.png',screen:'oslo',startsAt:'2026-09-09T00:00:00+02:00',endsAt:'2026-09-12T20:00:00+02:00'}],
    ['member-deals',{type:'benefit-roundup',eyebrow:'MEMBER DEALS',title:'Your membership.\nPut it to work.',body:'Three offers worth checking before your next software bill. Eligibility and provider terms apply.',cards:[
      {heading:'Miro',detail:'$1,000 in credits to map ideas and plan your next product move.',note:'For eligible startups with fewer than 30 employees.'},
      {heading:'Notion',detail:'Up to six months free, with Notion AI included.',note:'Eligible startups only. Application required.'},
      {heading:'Microsoft',detail:'Azure credits and technical support for your next stage.',note:'Benefits depend on eligibility and programme tier.'}
    ],cta:'Explore your member deals',url:'https://app.notion.com/p/9b6b4345ef8c4a6e8352eeaff5c37c77'}],
    ['news-saro',{type:'member-news',eyebrow:'COMMUNITY IN THE NEWS',title:'Saro Robotics\nheads to Techstars.',body:'From Startuplab’s Student Accelerator to a three-month programme in the US. Next up: taking industrial pipe-inspection robots further.',detail:'Shifter · 8 September 2026',location:'Photo: Press / via Shifter',cta:'Read the story in Shifter',url:'https://www.shifter.no/nyheter/robotselskap-fra-ntnu-valgt-ut-til-techstars-inspirert-av-cognite/474851',image:'assets/photos/news-saro.jpg'}],
    ['departures',{type:'transit',eyebrow:'LEAVING THE LAB',title:'Your next departure.',body:'Metro and tram from Forskningsparken. Buses from Gaustad.',cta:'Plan your journey',url:'https://entur.no/nearby-stop-place-detail?id=NSR:StopPlace:59600',screen:'oslo'}],
    ['useful-introduction',{type:'welcome',eyebrow:'FOUNDERS. INVESTORS. VISITORS. YOU.',title:'One useful\nintroduction.',body:'Before you leave, ask someone what they are building. Then think of one person they should meet.',detail:'Good companies grow through good conversations.',cta:''}],
    ['community-ask',{type:'request',eyebrow:'A SMALL ASK. A BIG DIFFERENCE.',title:'What could this\nroom help you solve?',body:'A first customer. An honest product review. Someone who has done it before. Tell the Startuplab team what you need.',detail:'Be specific: one question, one next step.',cta:'Start a conversation today'}]
  ].map(([id,content])=>({id:`member-review-${id}`,content:{...base,...content}}));
}

export const MEMBER_DESCRIPTIONS={
  'member-review-pradeep-team-os':['team-os','AI X · Pradeep / Team OS','Temaforslag 1, basert på Pradeeps e-post 3. september. Dato og påmeldingslenke er ikke bekreftet.'],
  'member-review-pradeep-ai-product':['ai-revenue','AI X · Pradeep / AI til inntekter','Alternativt tema for samme kommende session. Basert på Pradeeps e-post og tittelen på presentasjonen han delte; selve vedlegget er ikke lest. Spørsmålene på sliden er redaksjonelle forslag.'],
  'member-review-operators-bergen':['bergen-event','Bergen · Operators’ Sessions','Bekreftet Luma: 11. september, 13:30–15:00. Aurora Klæboe Berg, VP Operations i Tana.'],
  'member-review-mad-hack-agentic-loops':['mad-hack','AI Mad Lab · Agentic Loops','12. september, 10:00–20:00. Original arrangørgrafikk, egen AI Mad Lab-logo og vanlig QR. Påmelding krever arrangørens godkjenning.'],
  'member-review-member-deals':['deals','Tre medlemsfordeler','Miro, Notion og Microsoft. Sjekket mot intranettet og leverandørenes vilkår 9. september. Ingen interne rabattkoder i QR eller eksport.'],
  'member-review-news-saro':['news','Medlemsnytt · Saro Robotics','Funnet i internt Slack #news og kontrollert mot Shifter 8. september. Foto fra artikkelen til lokal review; publiseringsrett bør avklares.'],
  'member-review-departures':['departures','Avganger · Forskningsparken og Gaustad','Datert Entur-snapshot til designreview. Åpne live-visningen for oppdaterte avganger; PNG blir aldri en live-feed.'],
  'member-review-useful-introduction':['introduction','Nytt konsept · én nyttig introduksjon','En enkel samtalestarter for medlemmer, investorer og besøkende. Ingen innlogging eller påmelding nødvendig.'],
  'member-review-community-ask':['community-ask','Nytt konsept · hva trenger du hjelp med?','Inviterer til konkrete behov. En senere serie kan vise ett faktisk medlemsbehov av gangen, med eier og utløpsdato.']
};
